wandb_version: 1

batch_size:
  value: 64
epochs:
  value: 10
lr:
  value: 0.006567730635979071
model:
  value:
    dropout_per_layer:
    - 0.15
    - 0.15
    - 0.15
    - 0.15
    - 0.15
    no_units_per_layer:
    - 784
    - 512
    - 256
    - 128
    - 64
    - 10
    skip_connections: []
momentum:
  value: 0.04737571165056452
nesterov:
  value: true
optimizer_name:
  value: SGD
weight_decay:
  value: 0
