wandb_version: 1

batch_size:
  desc: null
  value: 128
epochs:
  desc: null
  value: 10
lr:
  desc: null
  value: 0.009172187497263914
model:
  desc: null
  value:
    dropout_per_layer:
    - 0.15
    - 0.15
    - 0.15
    - 0.15
    - 0.15
    no_units_per_layer:
    - 784
    - 512
    - 256
    - 128
    - 64
    - 10
    skip_connections: []
momentum:
  desc: null
  value: 0.07849143288832348
nesterov:
  desc: null
  value: false
optimizer_name:
  desc: null
  value: SGD
weight_decay:
  desc: null
  value: 0.016048826803967856
_wandb:
  desc: null
  value:
    python_version: 3.10.8
    cli_version: 0.15.12
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1699901076.738966
    t:
      1:
      - 1
      - 2
      - 3
      - 41
      - 51
      - 55
      2:
      - 1
      - 2
      - 3
      - 41
      - 51
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.10.8
      5: 0.15.12
      8:
      - 3
      - 5
      13: windows-amd64
