wandb_version: 1

batch_size:
  value: 64
epochs:
  value: 10
lr:
  value: 0.0033065767081926776
model:
  value:
    dropout_per_layer:
    - 0.15
    - 0.15
    - 0.15
    - 0.15
    - 0.15
    no_units_per_layer:
    - 784
    - 512
    - 256
    - 128
    - 64
    - 10
    skip_connections: []
momentum:
  value: 0.02186066520846104
nesterov:
  value: false
optimizer_name:
  value: SGD
weight_decay:
  value: 0.005
