wandb_version: 1

batch_size:
  value: 256
epochs:
  value: 3
learning_rate:
  value: 0.026172624468404335
momentum:
  value: 0.01964499304214733
nesterov:
  value: true
no_units_per_layer:
  value:
  - 784
  - 128
  - 64
  - 10
optimizer:
  value: sgd
weight_decay:
  value: 0.090403235101392
