wandb_version: 1

batch_size:
  value: 32
epochs:
  value: 3
learning_rate:
  value: 0.005162988587689474
momentum:
  value: 0.05940540180807458
nesterov:
  value: true
no_units_per_layer:
  value:
  - 784
  - 128
  - 64
  - 10
optimizer:
  value: sgd
weight_decay:
  value: 0.13299228913758696
