wandb_version: 1

batch_size:
  value: 32
epochs:
  value: 3
learning_rate:
  value: 0.06799117017967227
momentum:
  value: 0.09444682328607076
nesterov:
  value: true
no_units_per_layer:
  value:
  - 784
  - 128
  - 64
  - 10
optimizer:
  value: sgd
weight_decay:
  value: 0.3181280131775176
