wandb_version: 1

batch_size:
  value: 256
epochs:
  value: 3
learning_rate:
  value: 0.09141450024594926
momentum:
  value: 0.02677584202236593
nesterov:
  value: true
no_units_per_layer:
  value:
  - 784
  - 128
  - 64
  - 10
optimizer:
  value: sgd
weight_decay:
  value: 0.31168138678989266
