wandb_version: 1

batch_size:
  value: 128
epochs:
  value: 3
learning_rate:
  value: 0.07746254437491845
momentum:
  value: 0.03481072613483918
nesterov:
  value: true
no_units_per_layer:
  value:
  - 784
  - 128
  - 64
  - 10
optimizer:
  value: sgd
weight_decay:
  value: 0.3566438555606623
