wandb_version: 1

batch_size:
  value: 64
epochs:
  value: 3
learning_rate:
  value: 0.008831204588514979
momentum:
  value: 0.02064495427594827
nesterov:
  value: true
no_units_per_layer:
  value:
  - 784
  - 128
  - 64
  - 10
optimizer:
  value: sgd
weight_decay:
  value: 0.25719937109212465
