wandb_version: 1

batch_size:
  value: 256
epochs:
  value: 10
lr:
  value: 0.00385466568061023
model:
  value:
    dropout_per_layer:
    - 0.15
    - 0.15
    - 0.15
    - 0.15
    - 0.15
    no_units_per_layer:
    - 784
    - 512
    - 256
    - 128
    - 64
    - 10
    skip_connections: []
momentum:
  value: 0.035357093456358825
optimizer_name:
  value: RMSprop
weight_decay:
  value: 0.01
