wandb_version: 1

batch_size:
  value: 128
epochs:
  value: 10
lr:
  value: 0.009474133071481415
model:
  value:
    dropout_per_layer:
    - 0.15
    - 0.15
    - 0.15
    - 0.15
    - 0.15
    no_units_per_layer:
    - 784
    - 512
    - 256
    - 128
    - 64
    - 10
    skip_connections: []
momentum:
  value: 0.008469687204356518
optimizer_name:
  value: RMSprop
weight_decay:
  value: 0.01
